/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include<led.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	led_init(LED_RED);    // Pin 14

		    led_init(LED_GREEN);  // Pin 12

		    led_init(LED_ORANGE); // Pin 13

		    led_init(LED_BLUE);   // Pin 15



		    // 2. Set initial state: Start with Red and Green ON, others OFF

		    led_on(LED_RED);

		    led_on(LED_GREEN);

		    led_off(LED_ORANGE);

		    led_off(LED_BLUE);



		    while(1)

		    {

		        // 3. Wait for 1 second

		        DelayMs(1000);



		        // 4. Toggle all 4 LEDs

		        // Red/Green will turn OFF, Orange/Blue will turn ON

		        led_toggle(LED_RED);

		        led_toggle(LED_GREEN);

		        led_toggle(LED_ORANGE);

		        led_toggle(LED_BLUE);



	/*led_init(LED_GREEN);
	led_init(LED_ORANGE);
	led_init(LED_RED);
	led_init(LED_BLUE);

	while(1){
		led_toggle(LED_GREEN);
		led_toggle(LED_ORANGE);
		led_toggle(LED_RED);
		led_toggle(LED_BLUE);
		DelayMs(2000);*/
	}
}











